version: '3.8'

services:
  java-service:
    build: ./RentalService
    image: battlcall/servicejava:latest
    ports:
      - "8080:8080"
    networks:
      - rental-network

  php-service:
    build: ./phpService
    image: battlcall/servicephp:latest
    ports:
      - "8082:80"
    networks:
      - rental-network

networks:
  rental-network:
    driver: bridge
